# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-15 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('system', models.CharField(choices=[('windows', 'windows'), ('linux', 'linux'), ('mac', 'mac')], max_length=30, verbose_name='系统')),
                ('disk_partition', models.CharField(max_length=100, verbose_name='磁盘分区')),
                ('disk_capacity', models.FloatField(blank=True, verbose_name='磁盘容量(单位Gb)')),
                ('record_time', models.TimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '主机磁盘信息',
                'verbose_name_plural': '主机磁盘信息',
            },
        ),
        migrations.AlterUniqueTogether(
            name='hostmodel',
            unique_together=set([('ip', 'disk_partition')]),
        ),
    ]
