# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_auto_20190515_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmodel',
            name='ip',
            field=models.GenericIPAddressField(unpack_ipv4=True, verbose_name='ip地址'),
        ),
    ]
