# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-15 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0006_auto_20190515_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmodel',
            name='record_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
